// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FilRougeMVC.Data;

public partial class Adress
{
    public int Id { get; set; }

    public string Appartement { get; set; } = null!;

    public string Rue { get; set; } = null!;

    public string Ville { get; set; } = null!;

    public string CodePostal { get; set; } = null!;

    public string Pays { get; set; } = null!;

    public virtual ICollection<Lecteur> Lecteurs { get; set; } = new List<Lecteur>();
}