// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FilRougeMVC.Data;

public partial class Auteur
{
    public int Id { get; set; }

    public string Nom { get; set; } = null!;

    public string Prenom { get; set; } = null!;

    public string Email { get; set; } = null!;

    public string Telephone { get; set; } = null!;

    public string Grade { get; set; } = null!;

    public virtual ICollection<Livre> Livres { get; set; } = new List<Livre>();

    [NotMapped]
    public string FullName
    {
        get
        {
            return Prenom + " " + Nom;
        }
    }
}