// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FilRougeMVC.Data;

public partial class Emprunt
{
    public int Id { get; set; }

    public DateTime DateEmprunt { get; set; }

    public DateTime DateRetour { get; set; }

    public int LecteurId { get; set; }

    public int LivreId { get; set; }

    public virtual Lecteur Lecteur { get; set; } = null!;

    public virtual Livre Livre { get; set; } = null!;
}