// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FilRougeMVC.Data;

public partial class Lecteur
{
    public int Id { get; set; }

    public string Nom { get; set; } = null!;

    public string Prenom { get; set; } = null!;

    public string Email { get; set; } = null!;

    public string Telephone { get; set; } = null!;

    public string MotDePasse { get; set; } = null!;

    public int AdresseId { get; set; }

    public virtual Adress Adresse { get; set; } = null!;

    public virtual ICollection<Emprunt> Emprunts { get; set; } = new List<Emprunt>();
}