// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FilRougeMVC.Data;

public partial class Livre
{
    public int Id { get; set; }

    public string Titre { get; set; } = null!;

    public int NombrePages { get; set; }

    public int StatutDuLivre { get; set; }

    public int EtatDuLivre { get; set; }

    public int AuteurId { get; set; }

    public int DomaineId { get; set; }

    public virtual Auteur Auteur { get; set; } = null!;

    public virtual Domaine Domaine { get; set; } = null!;

    public virtual ICollection<Emprunt> Emprunts { get; set; } = new List<Emprunt>();
}