// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FilRougeMVC.Data;

public partial class EmpruntViewModel
{


    public DateTime DateEmprunt { get; set; }

    public DateTime DateRetour { get; set; }

    public int LecteurId { get; set; }

    public int LivreId { get; set; }


}