// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FilRougeMVC.Data;

public partial class LivreViewModel
{


    public string Titre { get; set; } = null!;

    public int NombrePages { get; set; }

    public int StatutDuLivre { get; set; }

    public int EtatDuLivre { get; set; }

    public int AuteurId { get; set; }

    public int DomaineId { get; set; }

}